#include <xc.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include "system_config.h"
#include "system/system.h"
#include "usb/usb_device.h"
#include "usb/usb_device_hid.h"
#include "app_keyboard.h"
#include "app.h"
#include "bsp.h"


/*
*********************************************************************************************************
*                                           GLOBALS
*********************************************************************************************************
*/
extern APP_DATA appData;





/*
*********************************************************************************************************
*                                          ApplicationUSBDeviceHIDEventHandler
*
* Description : This event handler will handle all device layer events. Event callback generated by USB 
*               device layer.
* Arguments   : 
*********************************************************************************************************
*/
USB_DEVICE_HID_EVENT_RESPONSE ApplicationUSBDeviceHIDEventHandler(
                                 USB_DEVICE_HID_INDEX hidInstance,
                                 USB_DEVICE_HID_EVENT event,
                                 USB_DEVICE_HID_CONTROL_TRANSFER_HANDLE controlTransferHandle,
                                 void * eventData, 
                                 uintptr_t userData)
{
   APP_DATA * pUserAppData = (APP_DATA *)userData;

   switch(event)
   {
      case USB_DEVICE_HID_EVENT_REPORT_SENT:
         /* This means the mouse report was sent.
         We are free to send another report */
         pUserAppData->isReportSentComplete = true;
         break;
      case USB_DEVICE_HID_EVENT_REPORT_RECEIVED:
         /* This means we have received a report */
         pUserAppData->isReportReceived = true;
         break;
      case USB_DEVICE_HID_EVENT_SET_IDLE:
         /* For now just accept this as is */
         USB_DEVICE_HID_ControlStatus(hidInstance, controlTransferHandle,
            USB_DEVICE_CONTROL_STATUS_OK);
         break;
      default:
         break;
   }

   return USB_DEVICE_HID_EVENT_RESPONSE_NONE;
}

/*
*********************************************************************************************************
*                                          ApplicationUSBDeviceEventHandler
*
* Description : This event handler will handle all device layer events. Event callback generated by USB 
*               device layer.
* Arguments   : 
*********************************************************************************************************
*/
void ApplicationUSBDeviceEventHandler(USB_DEVICE_EVENT event, USB_DEVICE_EVENT_DATA * eventData)
{
   switch(event)
   {
      case USB_DEVICE_EVENT_RESET:
      case USB_DEVICE_EVENT_DECONFIGURED:
   
         /* Device got deconfigured */
         appData.isConfigured = false;
         BSP_SwitchONLED ( LED_2);
         BSP_SwitchOFFLED ( LED_3);
         break;
      case USB_DEVICE_EVENT_CONFIGURED:
         /* Device is configured */
         if(eventData->eventConfigured.configurationValue == 1)
         {
            appData.isConfigured = true;
   
            BSP_SwitchOFFLED ( LED_2 );
            BSP_SwitchONLED ( LED_3 );
   
            /* Register the Application HID Event Handler. */
            USB_DEVICE_HID_EventHandlerSet(appData.hidInstance,
               ApplicationUSBDeviceHIDEventHandler, 
               (uintptr_t)&appData);
         }
         break;
      case USB_DEVICE_EVENT_SUSPENDED:
         BSP_SwitchONLED ( LED_2 );
         BSP_SwitchONLED ( LED_3 );
         break;
      case USB_DEVICE_EVENT_RESUMED:
      case USB_DEVICE_EVENT_ATTACHED:
      case USB_DEVICE_EVENT_DETACHED:
      case USB_DEVICE_EVENT_ERROR:
      default:
         break;
   
   }
}

